function Fw = Engine_Force(highest_torque, gear, Final_ratio, gear_ratios, Tire_radious)
    % Calculate the force generated by the engine for the current RPM
    % and Gear
    Fw = highest_torque * Final_ratio * gear_ratios(gear) / Tire_radious;
end  